### PR TITLE
Start on interim compiler

### LINKED ISSUE #873: PC files need to be compiled into intermediate format
PC -> intermediate format -> code.

This is primarily to make it easier for creating new compilers into language targets. Reason for this is that translations will largely be similar to one another. E.g: the compiled CSS output, and the elements that use those styles. We can also compile information about props that can be used for languages that are strongly typed. 

This will also greatly simplify the React compiler.

Considerations:

- VueJS
- SvelteJS
- FFI

### PR DESCRIPTION
**Pull request by crcn**
Fixes #873. This is an MVP (not expecting API to be polished up) - will likely be shaped up depending on target language needs. Next thing after this PR would be to stress test the API by refactoring React compiler + creating a new target that's a bit chewier (Ruby, Python, something server-side).

Pseudocode API:

```javascript
import {  translateIntermediate }  from "paperclip-compiler-interm";
import {  createEngineDelegate } from "paperclip";

const engine = createEngineDelegate();
const ast = engine.parseContent("/entry.pc");

const interm = translateIntermediate(ast);

const reactCode = translateReactCode(interm);

fs.writeFileSync("something.tsx", reactCode);

```

TODOs:

- [x] interim compiler
  - [x] should contain source maps of AST
  - [x] should contain lightly transformed AST (should contain CSS scopes and such)
  - [x] should contain computed CSS
- [x] builder
  - [x] should do the work writing CSS from engine
  - [ ] ~identify language + additional features to go with it (maybe smth like `[js|ruby|py]-extension`) such as es5 compilation, auto-inclusion of CSS in JS imports. It _may_ be best to have _base_ compilers that these individual compilers can so that no assumptions are made about framework targets in general. **~
- [ ] ~_base_ JS compiler that enables:~
  - [ ] ~inclusion of CSS files if flag is specified (necessary for code splitting + async import)~
- [x] Update React compiler to use interm compiler
- [ ] should be able to embed all assets into files
- [ ] should be able to combine all CSS into one file
- [ ] should able to define source maps file name
- [ ] source be able to move assets to common directory (including CSS)
- [x] update compiler to use line + column
- [x] use source maps
- [x] Update CLI to use builder
- [x] Update loader to use builder
- [x] auto-scan for compilers, don't require compiler name
  - [x] enable for multiple compilers
- [x] Update docs
  - [x] ensure that `class` instead of `className` is used
  - [ ] show section about how to use with React (`{class?} {className}` combo)
- [x] Fix website styling (font + assets not loading)
- [x] live preview should work
  - [x] ensure that inspector shows up
  - [x] ensure that VS Code extension isn't throwing error
  - [x] ensure that frames are written to VS Code extension
  - [x] meta clicking elements should work
  - [x] "Open in browser" button needs to work
  - [x] Ensure that error banner is showing
- [x] `paperclip dev` should work
- [x] Fix double clicking into element

### CODE REVIEW

**Comment by crcn** [comment]
CC @zephraph just hacking on this, lmk if you want to take over.

**Comment by crcn** [comment]
This will likely be split up into _three_ parts:

1. The interm compiler (makes it easier to consume AST + does some light transformations)
2. language compilers (consumers of interm compiler)
3. a builder (combines interm compiler + language compiler)


The interm compiler will produce JSON that is _just about_ a 1:1 map with the original AST - the only thing that will be fully computed is the CSS since this output should be the same across all language targets (particularly because of behavior expectations). The HTML on the other hand will pretty much be a 1:1 map with the AST, with some additional metadata attached to each node so that we can easily link CSS selectors to their corresponding element. 

☝️ At this point the only thing that a compiler would need to do is produce primitive components. The code for this I'd imagine would be pretty easy to write since all of the work should pretty much be done with the interm compiler. 

#### Combining the interm compiler + code compiler + builder

Some pseudocode of a compiler:

```javascript
export const extension = ".rb";
export const compile = (info) => {
  // .. compile it

  return {
    code,
    sourceMaps
  }
}
```

This being defined within a node module and included in the PC config:

```javascript
{
  compiler: {
    name: "paperclip-ruby-compiler"
  }
}
```

### Considerations

- further transformations (es6 -> es5). This can be included in the compiler, I think (at least for v1).

**Comment by crcn** [comment]
Some compiler pseudocode that involves a base compiler:

```javascript
import { transform } from "paperclip-js-compiler-utils";

export const compile = (interm) => transform({
  jsCode: "const a = 'b'",
  interm,
 options: { target: "es5", includeCSSImport: true }
});
```

☝️ poor naming but shape is somewhat in the right direction, I think.

**Comment by crcn** [comment]
Regarding SFC enforcement for frameworks such as Vue, I think one _possible_ solution to this is to write multiple component files from one PC file. For example:

```html
<div export component as="A">
</div>
<div export component as="B">
</div>
```

May produce:

```
component.A.vue
component.B.vue
```

☝️ smth like this means that that file generation will likely need to be controlled by the compiler. E.g:

```javascript
export const compile = (module) => {
  return translateComponents(module).map(component => ({ file: generatedFileNameHere" });
}
```


EDIT: I take this back -- there are some wrinkles with this approach, primarily around `paperclip-loader`. Main issue is when we're importing `.pc` files directly in other files.

**Comment by crcn** [comment]
- [ ] generalize test suite & place in separate directory. API should look something like this:

```html
test-paperclip-compiler [COMPILER_REACT_NAME]
```

**Comment by crcn** [comment]
- [x] ensure that `<fragment export component as="Component" />` works
- [x] ensure that `<fragment export component as="Component" {tagName?} />` works

**Comment by crcn** [comment]
- [ ] include source maps with compiled output
- [ ] include VS Code map with compiled output
- [ ] use same test suite as Paperclip package - (ensures that DSL changes are aligned with compiled output. We can take test source & match with test outputs for this).
- [ ] update typed definition compiler
- [ ] `--exclude` flag for CLI output (`--exclude="d.ts,css"`)
- [ ] `--include` flag for CLI output
- [ ] typed definition files should be generated always. Use exclusion / inclusion flags for file generation.

**Comment by crcn** [comment]
- [ ] ~option to use `class` or `className` in compiler specifically for React. Should be reflected in runtime, and also used in interm.~

This can be fixed if we just use `class`, and then let the user define `className` for React support. For example:

```html
<div export component as="Test" class="{class?} {className?}">
  Hello world
</div>

<Test>
   <style>
     color: red;
   </style>
</Test>
```

☝️ `style` blocks like this would pass in `class`, the `className` is for exposure to React for additional styling -- particularly for third-party libraries that pass in `className`.

This way the interm compiler can look for `class` attributes and just leave them be if they're defined on component instances - they'll map to the native element. And since we know when a native element is being rendered, we can simply rename `class` attributes to `className`.

**Comment by just-be-dev** [comment]
> Regarding SFC enforcement for frameworks such as Vue, I think one _possible_ solution to this is to write multiple component files from one PC file. For example:
> 
> ```
> <div export component as="A">
> </div>
> <div export component as="B">
> </div>
> ```
> 
> May produce:
> 
> ```
> component.A.vue
> component.B.vue
> ```
> 
> point_up smth like this means that that file generation will likely need to be controlled by the compiler. E.g:
> 
> ```js
> export const compile = (module) => {
>   return translateComponents(module).map(component => ({ file: generatedFileNameHere" });
> }
> ```
> 
> EDIT: I take this back -- there are some wrinkles with this approach, primarily around `paperclip-loader`. Main issue is when we're importing `.pc` files directly in other files.

Yeah, I wouldn't think you'd want the interim compiler to care about either the file generation nor the specifics of how a pc file should break down into other component files. It seems like that responsibility would be delegated to the consumer of the intermediate layer.

**Comment by crcn** [comment]
> Yeah, I wouldn't think you'd want the interim compiler to care about either the file generation nor the specifics of how a pc file should break down into other component files. It seems like that responsibility would be delegated to the consumer of the intermediate layer.

Yep, totally. Working on getting the interim layer to be a 1:1 with the AST, but with a better DX.

**Comment by crcn** [comment]
- [ ] `embedAssets` flag for compiler option (necessary esp for node modules)

**Comment by crcn** [comment]
- [ ] `assetsDirectory` option

**Comment by crcn** [comment]
@zephraph what do you think about auto-loading compilers instead of needing to define them in `paperclip.config.json`? That way the DX is simply

```
yarn install paperclip paperclip-compiler-jinja
```

```
yarn paperclip build
```

To generate [Jinja](https://jinja.palletsprojects.com/en/3.0.x/templates/) templates. Another thought is to use _multiple_ compilers if present, for example:

```
yarn install paperclip paperclip-compiler-jinja paperclip-compiler-react
```

```
yarn paperclip build
```

May produce:

```
template.pc.jinja
template.pc.js
template.pc.js.map
template.pc.d.ts
template.pc.css # used between JS and Jinja
```

Developers may have the option to generate only specific files like so:

```
yarn paperclip build --targets=jinja,css,js
```

Thoughts?

**Comment by just-be-dev** [comment]
Yeah, sounds like a good idea to me.

**Comment by crcn** [comment]
Moving onto assets now, there will need to be some flexibility about what to do with them. Here's a rundown of functionality off the top of my head:

- ability to embed assets directly in CSS & HTML files. This is necessary for NPM modules - PC modules will need to work out of the box.
- Ability to dump assets in an assets directory
  - Ability to specify prefix for assets (hostname + asset path)
- Ability to leave assets as-is
  - In this case, the assumption is that a bundler is in use. 

All of this will probably be specified in the config. Here's an idea:

```javascript
{
  compiler: {
     react: {
        // react options
     }
  },

  assets: {

   // false by default
   module: true | false,

    // embed assets that don't exceed this max file size. This supersedes module=true
    embedMaxFileSize: 0,
     
    // directory where files are emitted that don't exceed embedMaxFileSize
    outputDirectory: "./assets",

     // checksum names based on content
    checksumNames: true,

   // prefix to use for files that are emitted in outputDirectory. Necessary
   // for things like CDN
   prefix: process.env.ASSET_PREFIX

   combineCSS: true
  },
}
```

As for a compiled example, here's might be `module=true` mode:

```javascript
const getDefault = (module) => module.default || module;
export const Component = () => React.createElement("img", { src: getDefault(require("./asset.svg")) });
```

`embedMaxFileSize > 0` option:

```javascript
const getDefault = (module) => module.default || module;
export const Component = () => React.createElement("img", { src: "data:image/svg+xml,%3Csvg%20width%3D%....." });
```

`embedMaxFileSize=0 && prefix=http://cdn.app.com/assets/` option:

```javascript
const getDefault = (module) => module.default || module;
export const Component = () => React.createElement("img", { src: "http://cdn.app.com/assets/asset.svg" });
```

#### Considerations

- if `module=false` then CSS files shouldn't be imported in the compiler output
- Embedded assets should happen in the interim layer. `module=true|false` should happen in the compiler layer (since this is target specific).
- Default behavior should be to leave assets as-is
- If `outputDirectory` is specified but not `prefix`, then assets should be resolved in _relation_ to the emitted JS files.

**Comment by crcn** [comment]
- [x] fix error that's popping up for tailwind example

Screen Shot 2021-12-05 at 10 57 16 PM

**Comment by crcn** [comment]
- https://github.com/clap-rs/clap

**Pull request merged**
